Repository Arquisoft/wichat_es3b, pull requests merged in 2025-05, with the labels that each got.

#283 Eliminar cors
  .idea/misc.xml
  wikiquestionservice/package.json
  wikiquestionservice/wikiQuestion-service.js
Labels: :hammer_and_wrench: backEnd, :globe_with_meridians: wikidata

#291 Actualizada tabla explicatoria diagrama webapp game
  docs/src/05_building_block_view.adoc
Labels: :bookmark_tabs: documentation

#295 Aumento de coverage en algunos componentes de webapp sin cubrir
  webapp/public/favicon.ico
  webapp/public/index.html
  webapp/src/components/game-history/game-history.js
  webapp/src/components/game-history/game-history.test.js
  webapp/src/components/gameSettingsSidebar/GameSettingsSidebar.test.js
Labels: ✅test

#296 Cargar preguntas de wikidata
  wikiquestionservice/package-lock.json
  wikiquestionservice/wikiQuestion-service.js
Labels: :hammer_and_wrench: backEnd, :file_cabinet: dataBase, :globe_with_meridians: wikidata

#286 Load tests zi
  .idea/misc.xml
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/apikey/0004_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/iniciarsesion/0007_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/play10qcountries/0008_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playsolo/0006_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playsolo/0015_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/recordedsimulation/0004_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/recordedsimulation/0006_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/recordedsimulation/0008_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/recordedsimulation/0030_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/register/0006_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/registrarseiniciar/0006_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/registrarseiniciar/0008_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/signin/0006_request.json
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/ApiKey.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/CargarAplicacion.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/IniciarSesion.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/LogOut.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Perfil.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Play10qCountries.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/PlaySolo.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Ranking.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Rankings.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Register.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/RegistrarseIniciar.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/SignIn.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/WichatSimulation.scala
Labels: carga 🔋

#293 Ajustes en el gateway y del dashboard para ver monitoreo en local
  gatewayservice/gateway-service.js
  gatewayservice/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  gatewayservice/package-lock.json
  gatewayservice/package.json
Labels: monitoring

#305 Terminados tests de carga, a falta de resolución de cuellos de botella
  gatling-tests/pom.xml
  gatling-tests/src/test/resources/data/users.csv
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/askllmduringgame/0002_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0010_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0012_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0014_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0016_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0018_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0019_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0021_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0022_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0024_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0025_request.json
  gatling-tests/src/test/resources/es/uniovi/arquisoft/wichat/loadtests/playvsai/0027_request.json
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/ApiKey.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/AskLLMDuringGame.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/CargarAplicacion.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/IniciarSesion.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/LogOut.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Perfil.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Play10qCountries.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/PlaySolo.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/PlayVSAI.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Ranking.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Rankings.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/Register.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/RegistrarseIniciar.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/SignIn.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/WichatSimulation.scala
  webapp/src/components/game/Game.js
  webapp/src/components/gameSettings/GameSettings.js
  webapp/src/components/languageChangeMenu/LanguageChangeMenu.js
  webapp/src/i18n.js
Labels: ✅test

#308 Evitar preguntas repetidas en primera instancia.
  wikiquestionservice/questiongenerator/questionGen.js
  wikiquestionservice/wikiQuestion-service.js
Labels: :hammer_and_wrench: backEnd, :file_cabinet: dataBase, :globe_with_meridians: wikidata

#321 Load bottleneck fixes
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/PlaySolo.scala
  gatling-tests/src/test/scala/es/uniovi/arquisoft/wichat/loadtests/PlayVSAI.scala
  webapp/e2e/steps/game.steps.js
  wikiquestionservice/wikiQuestion-service.js
  wikiquestionservice/wikiQuestion-service.test.js
Labels: ✅test

#328 Revision de la documentación
  docs/images/5.2_QuestionServiceDiagram.png
  docs/images/5_Overview_diagram.png
  docs/src/04_solution_strategy.adoc
  docs/src/05_building_block_view.adoc
  docs/src/08_concepts.adoc
Labels: :bookmark_tabs: documentation

#326 Cambio del punto 3 de la documentación
  docs/images/final-business-context-diagram-3.0.png
  docs/images/final-technical-context-diagram-3.1.png
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_context_and_scope.adoc
Labels: :bookmark_tabs: documentation
