Repository Arquisoft/wichat_es3b, pull requests merged in 2025-03, with the labels that each got.

#58 Implementados componentes de Login y AddUser
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/assets/global.css
  webapp/src/assets/img/logo_base.png
  webapp/src/assets/img/plató.jpg
  webapp/src/components/AddUser.js
  webapp/src/components/Login.js
  webapp/src/components/addUser/AddUser.js
  webapp/src/components/button/BaseButton.css
  webapp/src/components/button/BaseButton.js
  webapp/src/components/login/Login.css
  webapp/src/components/login/Login.js
  webapp/src/components/photoPanel/PhotoPanel.css
  webapp/src/components/photoPanel/PhotoPanel.js
  webapp/src/components/textField/WiChatTextField.css
  webapp/src/components/textField/WiChatTextField.js
  webapp/src/index.css
  webapp/src/pages/authForm/AuthForm.css
  webapp/src/pages/authForm/AuthForm.js
Labels: :framed_picture: frontEnd

#60 Añadido al punto nueve de la documentación el uso de Docker.
  docs/src/09_architecture_decisions.adoc
Labels: :bookmark_tabs: documentation

#66 Game front end
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/assets/global.css
  webapp/src/assets/img/coliseo.jpg
  webapp/src/assets/img/flags/if_spain_flag.png
  webapp/src/assets/img/flags/if_uk_flag.png
  webapp/src/components/Footer.js
  webapp/src/components/Nav.js
  webapp/src/components/addUser/AddUser.js
  webapp/src/components/button/BaseButton.css
  webapp/src/components/chatBubble/ChatBubble.css
  webapp/src/components/chatBubble/ChatBubble.js
  webapp/src/components/dropdown/Dropdown.css
  webapp/src/components/dropdown/Dropdown.js
  webapp/src/components/dropdown/dropdownButton/DropDownButton.js
  webapp/src/components/dropdown/dropdownButton/DropdownButton.css
  webapp/src/components/dropdown/dropdownContent/DropdownContent.css
  webapp/src/components/dropdown/dropdownContent/DropdownContent.js
  webapp/src/components/dropdown/dropdownItem/DropdownItem.css
  webapp/src/components/dropdown/dropdownItem/DropdownItem.js
  webapp/src/components/hintButton/HintButton.css
  webapp/src/components/hintButton/HintButton.js
  webapp/src/components/languageChangeMenu/LanguageChangeMenu.css
  webapp/src/components/languageChangeMenu/LanguageChangeMenu.js
  webapp/src/components/login/Login.css
  webapp/src/components/login/Login.js
  webapp/src/components/nav/Nav.css
  webapp/src/components/nav/Nav.js
  webapp/src/components/photoPanel/PhotoPanel.js
  webapp/src/i18n.js
  webapp/src/index.js
  webapp/src/locales/en.json
  webapp/src/locales/es.json
  webapp/src/pages/Home.js
  webapp/src/pages/authForm/AuthForm.js
  webapp/src/pages/game/Game.css
  webapp/src/pages/game/Game.js
  webapp/src/pages/home/Home.css
  webapp/src/pages/home/Home.js
Labels: :framed_picture: frontEnd

#85 Integracion BD y primera version servicio stats
  docker-compose.yml
  package-lock.json
  package.json
  users/statsservice/Dockerfile
  users/statsservice/package-lock.json
  users/statsservice/package.json
  users/statsservice/stat-model.js
  users/statsservice/stats-service.js
  webapp/Dockerfile
Labels: :file_cabinet: dataBase, 🐳docker

#125 Documentation 9.architecture decisions
  docs/src/09_architecture_decisions.adoc
Labels: :bookmark_tabs: documentation

#134 Stats service integration
  docker-compose.yml
  gatewayservice/gateway-service.js
  llmservice/llm-service.test.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/game-history/game-history.css
  webapp/src/components/game-history/game-history.js
  webapp/src/components/nav/Nav.js
  webapp/src/components/sidebar/Sidebar.js
  webapp/src/index.js
  webapp/src/pages/home/Home.js
  webapp/src/pages/profilePage/PerfilPage.js
Labels: :framed_picture: frontEnd

#152 Completada la lógica básica del juego y reorganizada interfaz
  webapp/src/components/Footer.js
  webapp/src/components/chatBox/ChatBox.css
  webapp/src/components/chatBox/ChatBox.js
  webapp/src/components/infoDialog/InfoDialog.css
  webapp/src/components/infoDialog/InfoDialog.js
  webapp/src/pages/game/Game.css
  webapp/src/pages/game/Game.js
  webapp/src/pages/profilePage/PerfilPage.js
Labels: 🎮game

#155 Terminados arreglos leves en la interfaz de usuario
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/addUser/AddUser.js
  webapp/src/components/authHeader/AuthHeader.css
  webapp/src/components/authHeader/AuthHeader.js
  webapp/src/components/dropdown/Dropdown.js
  webapp/src/components/dropdown/dropdownButton/DropDownButton.js
  webapp/src/components/dropdown/dropdownButton/DropdownButton.css
  webapp/src/components/dropdown/dropdownContent/DropdownContent.css
  webapp/src/components/dropdown/dropdownContent/DropdownContent.js
  webapp/src/components/languageChangeMenu/LanguageChangeMenu.js
  webapp/src/components/login/Login.css
  webapp/src/components/login/Login.js
  webapp/src/pages/authForm/AuthForm.css
  webapp/src/pages/authForm/AuthForm.js
  webapp/src/pages/game/Game.css
  webapp/src/pages/game/Game.js
Labels: :bug: bug, :framed_picture: frontEnd
